### ISSUE TITLE
Error : target label does not exist

### ISSUE THREAD

**Issue by Gyslain** [aRTy42/POE-ItemInfo#114]
Hi,
When I launch Run_ItemInfo.ahk script from Windows-10, I get this error message :
![image](https://user-images.githubusercontent.com/11692729/37922687-8e11f8c4-312d-11e8-8e21-25bf909af008.png)
Any Ideas to fix that?
Thanks

**Comment by aRTy42** [comment]
It looks like an issue with the user files, yet again.

Where is your script folder located?
Could there be remnants of a previous installation/download of the script?

**Comment by Gyslain** [comment]
> Where is your script folder located?

I've moved the folder in C:\POE-ItemInfo-master

>Could there be remnants of a previous installation/download of the script?

Yes, I installed item info months ago. I think I saw old files in Documents that I removed.

**Comment by aRTy42** [comment]
That folder name suggests you downloaded the "master branch" at some point, not a regular release.

Try deleting the "POE-ItemInfo-master" folder and download the latest release (3.2.00) from https://github.com/aRTy42/POE-ItemInfo/releases.
I'd recommend to extract it into a folder named "POE-ItemInfo" because thats what the auto-updater uses by default, but you can choose a different name. Note that the release download is not wrapped up in a folder, so don't choose "extract here" directly onto the C:\ drive or something.

**Comment by Gyslain** [comment]
> That folder name suggests you downloaded the "master branch" at some point, not a regular release.

Good point. I downloaded the 3.2.00 release, extracted to POE-ItemInfo on c:, but I still get the error message :( Also, I tried to run script as administrator, but that didn't help.

**Comment by aRTy42** [comment]
In your user folder at "Documents\PoE-ItemInfo\CustomMacros" there should be a .txt file, likely named "customMacros_example.txt". Did you try to add personal macros to it? If not, you can delete it and have the script recreate the file from its default, that should hopefully fix the issue. If you did add personal code let me know and we can look at the details.

**Comment by aRTy42** [comment]
I just now saw that the markup ate something of the path I gave you. Please note that I did not mean the regular install folder, but the user folder at "\Documents\ ..."

**Comment by Gyslain** [comment]
I haven't PoE-ItemInfo in my Documents folder (I can see Path of building folder).
Maybe a missing write right? But I can manually create new folders or files...

**Comment by aRTy42** [comment]
Write permission issues would explain it and sadly isn't uncommon. Creating the folder by hand won't solve it though. What is a bit weird is that my Path of Building isn't in my documents folder, but that might be something I personally changed at some point.

You should take a look if some AntiVir/Malware program is restricting the access of ahk.

**Comment by Gyslain** [comment]
Yeaah!! It was indeed a write permission issue! To fix it (sorry it's in french) : 
![image](https://user-images.githubusercontent.com/11692729/37929926-7fa0601e-3141-11e8-9a23-6d7bcbc257a5.png)
This is a Window defender shit which control permission of unknown apps...
Thanks aRTy42 for your help!

**Comment by Eruyome** [comment]
FYI this is described in the TradeMacro FAQ, maybe the ItemInfo github page should just link that FAQ somewhere since some issues and solutions apply to both projects. 
@aRTy42 we should think about where to link it. 

https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/FAQ#16-error-target-label-does-not-exist

https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ#20-critical-permission-error
