### ISSUE TITLE
Error 146 item info not working?

### ISSUE THREAD

**Issue by xDREADNOUGHTx** [aRTy42/POE-ItemInfo#26]
;How many ticks to wait before removing tooltip. 1 tick = 100ms. Example, 50 ticks = 5secends, 75 Ticks = 7.5Secends
ToolTipTimeoutTicks=150

 found this cant change ?

**Comment by xDREADNOUGHTx** [comment]
all others look like this 
(; How )  many ticks to wait before removing tooltip. 1 tick = 100ms. Example, 50 ticks = 5secends, 75 Ticks = 7.5Secends
ToolTipTimeoutTicks=150

**Comment by aRTy42** [comment]
You need to activate that feature (which above that part in the code). I would strongly recommend using the regular options instead of editing the file itself:
Run the script. Right click the script icon in the systray. Select "PoE Item Info Settings". Put a tick in the box "Use tooltip timeout" and set a tick amount.

Reopen this issue if that does not work for you.

**Comment by xDREADNOUGHTx** [comment]
Thing is scrip will not run m8
