### ISSUE TITLE
scrip will not run hot key up2date also?

### ISSUE THREAD

**Issue by xDREADNOUGHTx** [aRTy42/POE-ItemInfo#27]
error at line 148 
     as before it just don't run thank you for the work you did though I give up was a beautiful tool , sad to lose it..

**Comment by aRTy42** [comment]
If you get an error at that line, it is related to how you unpacked or started the script. With that error, the script is missing some of its files or can't find or access them.

You need to unpack the whole script so that it becomes a regular folder and then leave the .ahk-file in that folder. You can move the whole folder, but you can't move the script-file away from its resources.

You can create a shortcut to the .ahk-file and put that where ever you want though, like on your desktop.
