### ISSUE TITLE
Wrong number of affixes due to double overlap in hybrid affix

### ISSUE THREAD

**Issue by jn64** [aRTy42/POE-ItemInfo#31]
Here is an item with 6 affixes (confirmed by vendor offering 1 Orb of Augmentation), detected as 5 affixes (4 + 1 hybrid):

![image](https://cloud.githubusercontent.com/assets/23169302/20901105/f2e0749e-bb6b-11e6-8582-2b539554dc21.png)

From what I can tell it has:
- X% increased Armour prefix
- X% increased Armour, X% increased Stun and Block Recovery prefix
- X% increased Stun and Block Recovery suffix

but with these particular rolls it's impossible to determine that it's not only the 2 non-hybrid rolls.

Don't have any solution :( Just documenting it here since I could not find any existing issue on it.

**Comment by aRTy42** [comment]
Thanks for the report.
I'm aware of it and it's basically the reason I try to include "but be careful when dealing with composite affixes" or something alike whenever I talk about the scripts reliability. The script also miscounts in several cases where hybrid affixes overlap in a way that can be figured out, but that requires multiple back-and-forth checks.

GGG said they are at least considering to include more info in the clipboard or even distisguish displayed prefixes/suffixes, so that people and/or scripts have an easier time figuring out what is what. That was a few months ago though, but hey: fingers crossed.

**Comment by aRTy42** [comment]
Finally able to close this. woop woop!
