### ISSUE TITLE
Ailment avoid mods

### ISSUE THREAD

**Issue by 4GForce** [aRTy42/POE-ItemInfo#47]
I have those boots with " x% chance to Avoid being Frozen " ( see attachment )

I couldn't find any infos about item mods like this one,  It's only mentioned as a passive skill.

I was also wondering how the data text files ( in /data ) were generated,  were those fetched from somewhere or hand made ?

Any resources I should know of ?

I could process the mod without the value range, but I have no clue if it's a prefix or suffix.

Any suggestions ?

![avoidailmentboots](https://cloud.githubusercontent.com/assets/25257792/22185541/13c25136-e0b6-11e6-8cbd-ad7eb0db6be6.jpg)

**Comment by aRTy42** [comment]
That's from the [Weeping Essence of Suffering](http://pathofexile.gamepedia.com/Weeping_Essence_of_Suffering). The script does not support essences yet.

The regular mods from essences have their own tiers which do not correspond with the regular mod tiers (which is pretty stupid), so the script usually has no chance to know what is what. The only option would be to start displaying multiple possibilities for mods, which is also rather weird.

The special mods from essences are supposed to be supported at some point. The wiki has a list of all essences on one page so one could theoretically make a list of all mods based on that and sort them. I also didn't find a proper list yet that tells me which essence mods are a prefix and which are a suffix. The only option I see there is to use poe.trade and look up all the special affixes one by one and look for 6 affix items to deduce prefix/suffix. (So basically essences are not supported because their tiers are a bitch, the other informations we need are tedious to aquire and the main use of the script is for dropped items which are not affected by essences. If you used an essence, you should know.)

I'm not sure how the data files were made initially. Any changes I've made to them happened manually though. The only exceptions are the three files for uniques, maps and divination cards, there are python scripts for those that I also update when necessary: https://github.com/aRTy42/scrape_poe_info

**Comment by 4GForce** [comment]
Oh my, probably the only essence I used in the game so far, forgot I ever did.

Thanks to your infos now I see the work required vs the feature value, I still came up with a quick fix that would be bypassed with further mod processing.

line 43
![avoidailmentboots_quickfix](https://cloud.githubusercontent.com/assets/25257792/22186752/99422932-e0c8-11e6-8201-458599fd0382.jpg)

**Comment by aRTy42** [comment]
I'd slightly adapt the wording, but that looks fine. Feel free to pull request it.

**Comment by 4GForce** [comment]
Go ahead with the wording, I'm french Canadian and my English is good but not fluid.
+1 ... I can talk to computers 0.o
