### ISSUE TITLE
Item info for shaped maps shows incorrect level and "upgrades to"

### ISSUE THREAD

**Issue by xanthics** [aRTy42/POE-ItemInfo#8]
See attached image, Shaped Jungle Valley (t6, level 73) upgrades to Arachnid Tomb. However iteminfo states it is level 68 and upgrades to beach(the unshaped map).

This happens with all shaped maps I have available to test with.

![screenshot-0008](https://cloud.githubusercontent.com/assets/3137623/19207890/631a5532-8ca9-11e6-949c-317d4915538c.png)

**Comment by aRTy42** [comment]
Thanks for the report. I looked and the wiki has documented the shaped maps, so I have the data needed to update the script.

**Comment by aRTy42** [comment]
I wanted to implement the data today and it turns out the shaped map wiki articles were created, but a lot of them are missing the upgrade info. The few ones I initially checked had them, so I assumed most should have them. Consequently that will leave a lot of "?" in the tooltip data for the script.

**Comment by Eruyome** [comment]
There are still problems with some maps, at least with Ivory Temple. It gets parsed as Temple Map. I fixed the Item.Name parsing for magic/rare items (`ParseItemName()`) a while ago and had to call this function a second time after knowing the number of affixes the item has. This second call happens after `ParseItemType()` is called, that function though is called before we know the number of affixes. 
But `ParseItemType()` would need the right `Item.Name` information to use it instead of the `NamePlateText` to parse `Item.SubType` and `Item.BaseType` without fail.   

I'm sure there are multiple solutions to this problem, the shortest ones more or less bandaid patches while the proper solutions could require a bit more refactoring. A shorter one could be not stopping the matching loop when a match is found but to continue until all maps have been compared, then the "better"/longer match is used if there are more than one...

**Comment by Eruyome** [comment]
Well, here is a quick bandaid-fix: https://github.com/aRTy42/POE-ItemInfo/pull/18/commits/cce341726547f6eee1deebca1bffa3a4c7350c5f

**Comment by aRTy42** [comment]
Well, the other solution would be to simply check "Ivory Temple Map" before "Temple Map". I had the same issue when implementing all the "Shaped ..." maps, because initially I had them in the "matchlist" after their corresponding map, so "Arcade Map" was matched against the item info before "Shaped Arcade Map" and consequently both types matched the regular map version.

The affix matching has similar manual fine tuning where shorter strings are checked later. I simply didn't notice the Ivory Temple Map/Temple Map issue before.

Edit: it's also the Vaal Temple Map

**Comment by Eruyome** [comment]
Well, the best solution would still be to get the correct Item.Name and  
 `RegExMatch(Trim(LoopField), "i)^"%Item.Name%"$", match)`

Or just `LoopField = Item.Name` 

Should be safer for future changes/additions.

**Comment by aRTy42** [comment]
Currently the map list is matched against the item name, not the other way around. Even if the item name was parsed/prepared correctly, the mismatch would occur, because the more general map name is listed earlier in the match list. Of course one could change the way the whole matching works. On the other hand, both methods can be broken by updates. The current variant is vulnerable to GGG renaming maps and other variants might get broken if any assumption about the original ctrl+c clipboard fails and/or when GGG makes changes to the clipboard (which are often enough not documented in the patch notes)

**Comment by Eruyome** [comment]
Do both and compare results :p

**Comment by aRTy42** [comment]
I double checked the map names with a program. Apart from the potential "Shaped" issue, there is:
- Temple Map conflicts with Ivory Temple Map and Vaal Temple Map,
- Lair Map with (Shaped) Spider Lair Map,
- Shrine with (Shaped) Overgrown Shrine Map.

In the previous map list, only the temple map was listed too early. I moved all three candidates to the very end though, for now.

**Comment by cirf** [comment]
tested all missing shaped maps upgrades and updated the wiki. An overview can be found her: https://pathofexile.gamepedia.com/User:Cirf_eu/ShapedMaps

**Comment by aRTy42** [comment]
Thanks
