### ISSUE TITLE
Misc HighlightItems problems

### ISSUE THREAD

**Issue by Nightblade** [aRTy42/POE-ItemInfo#83]
## Code
line 9836 of `POE-ItemInfo.ahk` doesn't do anything (unreachable?  probably my bad lol)
`			SendInput ^{sc02f}{Enter} ; sc021 = f  sc02f = v`

## Narrow Highlight
**Flasks:**
`Experimenter's Sulphur Flask of Iron Skin`  -> `"Experimenter's Sulphur Flask"`  (should be "Sulphur Flask"?)
`Experimenter's Quicksilver Flask` -> `"Experimenter's Quicksilver Flask"` (should be "Quicksilver Flask"?)
`Experimenter's Granite Flask` -> `""`

## Broad Highlight
*Flasks* -> `"Flask"` also matches flask recovery items.  Probably can't be helped?
`Rustic Sash` -> `" Belt"` also matches flasks but not rustic sash.
*Prophecy orbs* yield an empty result.
`Dazzling Ashscale Talisman`  -> `" Amulet"`  Doesn't match talisman items.  

**Boots:**
`Wrath Span Shagreen Boots` -> `"Evasion Rating:" `
`Domination Spur Conjurer Boots` -> `"Energy Shield:" `

**Comment by Eruyome** [comment]
I'll take a look at that.

Why do you think that line doesn't do anything? It pastes the text into the searchfield, works fine.

Flasks: I could add "Charges on use" or "Consumes". That should fix that.
Is some cases parsing the TypeName seems to go wrong.

The boots part is intended, take a look at the code, I added some comments explaining a few things.

```
; armour pieces are a bit special, the ingame information doesn't include "armour/body armour" or something alike.    

; we can use the item defenses though to match armour pieces with the same defense types (can't differentiate between "Body Armour" and "Helmet").
```

**Comment by Eruyome** [comment]
Some documentation while I look into this:

Function `ParseItemName()`

`Perpetual Granite Flask` fails completely because the AffixCount is 0.
`Perpetual Stibnite Flask of Dousing` has an AffixCount of 1.
So both seem to be missing 1, the exact AffixCount is really important for this parsing though.

Function `ParseFlaskAffixes()` should have an issue. `Increased Charge recovery` and `Increased Duration` are missing for example (text comparison if-else blocks).

**Comment by Eruyome** [comment]
I have fixed most of these things, I also had to check the string length of all terms since the search field has a 50 character limit. Prophecies could get long enough to exceed it since I used "add this prophecy" "merciless" "%name%". It's shortened a bit but this could still happen. Not sure if this should be further optimized.

I can't do anything about the belts, flasks have `Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.` in their item text. Also rustic sashes are the only belts not having `belt` anywhere. If we someday get logical operators this could be fixed.  

https://github.com/aRTy42/POE-ItemInfo/pull/84

**Comment by Nightblade** [comment]
> Why do you think that line doesn't do anything? It pastes the text into the searchfield, works fine.

Sorry @Eruyome, I didn't see this question until just now!

The `SendInput` loop on line 9833 is what's sending the text (terms) to POE.  The clipboard still contains the original raw item data.  Only the `{enter}` part is useful.

**Comment by Eruyome** [comment]
I still don't understand the issue. The search text is properly being inputted. Is the issue that the clipboard isn't resetted? Am I an idiot and don't see something obvious? Btw, the lines changed since I rewrote a lot.

EDIT: The clipboard is being resetted at the end.
EDIT2: Forget all that I said. `^{sc02f}` this is useless.
