### ISSUE TITLE
Suggestion/Request: Currency Ratios both ways

### ISSUE THREAD

**Issue by JaredKreft** [aRTy42/POE-ItemInfo#92]
Howdy! I love the tool, thank you for writing and maintaining it.

Request: When I search on a currency, like an Exalted orb, it will show me people on poe.trade selling an exalt and how many chaos I have to pay. I'd like a checkbox that will also show beside it people buying exalts for chaos and how many chaos they're paying. 

For each currency I search on, I'd like this. 

Seeing both the bid and the ask gives me a much better idea of what the currency ratio is at the moment, or just how much I can sell my currency for.

Thanks.

**Comment by Eruyome** [comment]
I may implement this, but so far I wanted to avoid it since it requires 2 seperate POST requests to poe.trade instead of one.
I'll put it on hold for now since I'm working on some other improvements.

EDIT: Didn't even notice that this was openend on the ItemInfo repo, I suppose it was intended for TradeMacro?

**Comment by JaredKreft** [comment]
Yes, it was, my apologies. Are you able to move it, or should I reopen it there?

**Comment by Eruyome** [comment]
Doesn't matter.
